### ISSUE TITLE
developer plus cert

### ISSUE THREAD

**Issue by SasiKiranK** [roma-glushko/magento2-cert-prof-dev-plus-exam#3]
hi

I dont think 2.3 is included in developer plus certification. as per the description it is only professional developer certification. 
please clarify

**Comment by roma-glushko** [comment]
Hi @SasiKiranK,
As for now, Magento DevPlus Cert is based on Magento 2.2 and for now this is the only not updated certification among other Magento Developer certifications. So feel free to use Magento 2.2 for your training 🙌 

From my side, I hope this certification will also be updated soon and will include such kind of topics like Declarative Schema. 

- Roman
